# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Install dependencies
COPY pyproject.toml README.md ./
COPY src/ ./src/
# No compiled extensions, use pip
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

# Default command
ENTRYPOINT ["cort-mcp"]
CMD ["--log=off"]
